const category = [
  {
    id: 1,
    name: "FLEXIMAA",
    category: "hoodies",
    size: "S",
    price: 67.00,
    stock: 0,
    image: "https://m.media-amazon.com/images/I/71WaqxJ748L._AC_UL320_.jpg",
    color: "Black",
    description: "Men's Cotton Hooded Neck Plain Sweatshirt/Hoodies",
    gender: "men",
  },
  {
    id: 2,
    name: "More & More",
    category: "hoodies",
    size: "S",
    price: 50.00,
    stock: 5,
    image: "https://m.media-amazon.com/images/I/711asRq+V8L._AC_UL320_.jpg",
    color: "White",
    description: "Unisex-Adult Cotton Hooded Neck Never Mind Printed Hoodie",
    gender: "men",
  },
  {
    id: 3,
    name: "More & More",
    category: "hoodies",
    size: "M",
    price: 50.00,
    stock: 10,
    image: "https://m.media-amazon.com/images/I/61RcCDrkbQL._AC_UL320_.jpg",
    color: "Radiam",
    description: "Unisex-Child Cotton Hooded Neck BTS Printed Hoodie",
    gender: "men",
  },
  {
    id: 4,
    name: "Champion",
    category: "hoodies",
    size: "XL",
    price: 82.00,
    stock: 10,
    image: "https://m.media-amazon.com/images/I/81o6rNIwBBL._AC_UL320_.jpg",
    color: "Gray",
    description: "Men's Powerblend Fleece Hoodie",
    gender: "men",
  },
  {
    id: 5,
    name: "Jerzees",
    category: "hoodies",
    size: "XL",
    price: 87.00,
    stock: 10,
    image: "https://m.media-amazon.com/images/I/81f-Xo4jzRL._AC_UL320_.jpg",
    color: "Blue",
    description: "Men’s Fleece Pullover Hoodie",
    gender: "men",
  },
  {
    id: 6,
    name: "Diverse",
    category: "shirts",
    size: "S",
    price: 62.00,
    stock: 10,
    image: "https://m.media-amazon.com/images/I/512pBZ7L-JL._AC_UL320_.jpg",
    color: "Brown",
    description: "Men Casual Shirt",
    gender: "men",
  },
  {
    id: 7,
    name: "Generic",
    category: "shirts",
    size: "M",
    price: 59.00,
    stock: 15,
    image: "https://m.media-amazon.com/images/I/41GqiVJC-5L._AC_UL320_.jpg",
    color: "Blue",
    description: "Casual LINE Shirt for Men || Blend Cotton Shirt",
    gender: "men",
  },
  {
    id: 8,
    name: "Amazon Brand - Inkast Denim",
    category: "shirts",
    size: "XL",
    price: 47.00,
    stock: 20,
    image: "https://m.media-amazon.com/images/I/71jMv3WbxaL._AC_UL320_.jpg",
    color: "Brown",
    description: "Men's Slim Fit Casual Shirt",
    gender: "men",
  },
  {
    id: 9,
    name: "Allen Solly",
    category: "tshirts",
    size: "S",
    price: 58.00,
    stock: 5,
    image: "https://m.media-amazon.com/images/I/81DM22NKVuL._AC_UL320_.jpg",
    color: "Yellow",
    description: "Men T-Shirt",
    gender: "men",
  },
  {
    id: 10,
    name: "RodZen",
    category: "tshirts",
    size: "M",
    price: 47.00,
    stock: 11,
    image: "https://m.media-amazon.com/images/I/619SqQW1NYL._AC_UL320_.jpg",
    color: "Blue",
    description: "Men's Cotton Half Sleeve Regular Fit Striped T-Shirt",
    gender: "men",
  },
  {
    id: 11,
    name: "Van Heusen",
    category: "tshirts",
    size: "XL",
    price: 62.00,
    stock: 21,
    image: "https://m.media-amazon.com/images/I/81tx-J6oidL._AC_UL320_.jpg",
    color: "Pink",
    description:
      "https://m.media-amazon.com/images/I/81tx-J6oidL._AC_UL320_.jpg",
    gender: "men",
  },
  {
    id: 12,
    name: "U.S. POLO ASSN.",
    category: "tshirts",
    size: "L",
    price: 79.00,
    stock: 25,
    image: "https://m.media-amazon.com/images/I/81ygBt2C91L._AC_UL320_.jpg",
    color: "Green",
    description: "Men T-Shirt",
    gender: "men",
  },
  {
    id: 13,
    name: "BLIVE",
    category: "tshirts",
    size: "XXL",
    price: 27.00,
    stock: 27,
    image: "https://m.media-amazon.com/images/I/71zaAby0-FL._AC_UL320_.jpg",
    color: "Yellow",
    description: "Printed Men Round Neck Full Sleeve T-Shirt",
  },
  {
    id: 14,
    name: "Dagcros",
    category: "hoodies",
    size: "M",
    price: 69.00,
    stock: 22,
    image: "https://m.media-amazon.com/images/I/510kn152g8L._AC_UL320_.jpg",
    color: "White",
    description: "Fleece Hooded Sweatshirt for Men's",
  },
  {
    id: 15,
    name: "More & More",
    category: "hoodies",
    size: "L",
    price: 79.00,
    stock: 27,
    image: "https://m.media-amazon.com/images/I/711asRq+V8L._AC_UL320_.jpg",
    color: "Yellow",
    description: "Unisex-Adult Cotton Hooded Neck Never Mind Printed Hoodie",
  },
  {
    id: 16,
    name: "ADRO",
    category: "hoodies",
    size: "XXL",
    price: 89.00,
    stock: 27,
    image: "https://m.media-amazon.com/images/I/51Q15IunfoL._AC_UL320_.jpg",
    color: "Black",
    description: "Men's Fleece Hooded Hoodie",
  },
  {
    id: 17,
    name: "ADRO",
    category: "jeans",
    size: "S",
    price: 99.00,
    stock: 23,
    image: "https://m.media-amazon.com/images/I/81qSCjIx-vL._AC_UL320_.jpg",
    color: "Blue",
    description: "Men's Skinny Jeans",
  },
  {
    id: 18,
    name: "Lawman",
    category: "jeans",
    size: "M",
    price: 99.00,
    stock: 33,
    image: "https://m.media-amazon.com/images/I/71op-uGmzuL._AC_UL320_.jpg",
    color: "Black",
    description: "Men's Skinny Jeans",
  },
  {
    id: 19,
    name: "ADRO",
    category: "jeans",
    size: "L",
    price: 99.00,
    stock: 23,
    image: "https://m.media-amazon.com/images/I/81qSCjIx-vL._AC_UL320_.jpg",
    color: "Blue",
    description: "Men's Skinny Jeans",
  },
  {
    id: 20,
    name: "Lawman",
    category: "jeans",
    size: "XL",
    price: 99.00,
    stock: 33,
    image: "https://m.media-amazon.com/images/I/71op-uGmzuL._AC_UL320_.jpg",
    color: "Black",
    description: "Men's Skinny Jeans",
  },
  {
    id: 21,
    name: "Lawman",
    category: "jeans",
    size: "XXL",
    price: 99.00,
    stock: 33,
    image: "https://m.media-amazon.com/images/I/71op-uGmzuL._AC_UL320_.jpg",
    color: "Black",
    description: "Men's Skinny Jeans",
  },
];

export default category;
